### ISSUE TITLE
How to use custom font in CometChat 

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#10]
I recently noticed that IOS SDK has received an update to use custom font in cometchat sdk.
When Android will get an update to use custom font ?

Or is there any other way available from that we can use custom font throughout the comet chat screens?

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 

We are currently working on the mechanism to have this feature in our SDK. I will be out in the next couple of releases.
