### ISSUE TITLE
Remove view profile section

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#12]
I wanted to remove the view profile section. How can I achieve this? Is there any way I can change the icons?
![screenshot_1544092542](https://user-images.githubusercontent.com/44662417/49578906-d29da400-f970-11e8-9d28-c39aea469fe1.png)

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 

You can hide RelativeLayout viewProfile in CCSettingActivity to remove ViewProfile section.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 
Thanks for your reply
We are not using ReadyUI. I am asking the solution for SDK integration.

**Comment by imdBhargav** [comment]
I am using the gradle dependency.
Could you please tell me how to change these icons ?

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

We currently don't have any mechanism which will allow you to change the icon in the CometChatUI directly. The only way to achieve this is to use CometChatUI as a module and making changes in the UI Source. You can find the UI source in CometChat SDK package downloaded from the following link:

http://secure.cometchat.com/

Feel free to contact us if you have any other queries.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil

I have tried implemeting UI source module but its giving me an error on startup. Please look at this issue #19 and #20
