### ISSUE TITLE
remove the Status message and online status 

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#13]
Can we remove the Status message and online status in view profile screen?

**Comment by jitvarpatil** [comment]
Yes. You can hide the corresponding views/layouts to remove the option from ReadyUI.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 
Thanks for your reply
We are not using ReadyUI. I am asking the solution for SDK integration.

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 

We currently don't have any mechanism which will allow you Status message and online status in view profile screen of CometChatUI. The only way to achieve this is to use CometChatUI as a module and making changes in the UI Source. You can find the UI source in CometChat SDK package downloaded from the following link:

http://secure.cometchat.com/

Feel free to contact us if you have any other queries.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 

I have tried implemeting UI source module but its giving me an error on startup. Please look at this issue #19 and #20
