### ISSUE TITLE
Remove Bots section

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#15]
Can we remove the Bots section?

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

You can disable Bots from CometChat admin panel to hide Bots section from the mobile platform. Following is the screenshot of Bots section in CometChat Admin panel. You can find a radio button on top-right of the screen to disable bots. 

![screen shot 2018-12-10 at 4 51 49 pm](https://user-images.githubusercontent.com/18652749/49729659-190a4000-fc9c-11e8-93d7-aa0184d13ae9.png)

Feel free to contact us if you have any other queries.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 

Thanks for your response. I will try this and let you know

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 

I have turned of boats from admin panel but after sometimes its again turned on automatically.
Please provide some solution

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

We are investigating this scenario. Please give us some time we will provide you with an update. Alternatively, you can hide the RelativeLayout viewBots from CCsettingsActivity. 

Thank You
