### ISSUE TITLE
get the click of row  items individually

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#18]
How can I get the individual click of an items present in one row. Suppose I want to open user profile screen from user photo. So How can I get the click of user photo etc.. How would I achieve this?

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

You can add onClickListner on individual views in onBindViewHolder of Adapter.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 
Yes you are right. But I am not using customize UI.
I am using cometchat SDK by adding its dependency in gradle file

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

We currently don't have any mechanism which will allow you the get individual click of items from the CometChatUI. The only way to achieve this is to use CometChatUI as a module and making changes in the UI Source. You can find the UI source in CometChat SDK package downloaded from the following link: 

http://secure.cometchat.com/ 

Feel free to contact us if you have any other queries.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 

I tried impleneting the CometChatUI module in my app as instructed by you but after that cometchat is start crashing. and I have posted these crash issues here. You can see issue numbers #19 and #20 for that. SO I am not able to apply cometchat module.

Please help
