### ISSUE TITLE
SqliteException

### ISSUE THREAD

**Issue by Pankaj0307** [cometchat-go/android-chat-sdk-demo#2]
Hi,

I am getting while launching the application : 

# no such table: ONE_ON_ONE_MESSAGE
while compiling: SELECT * from ONE_ON_ONE_MESSAGE WHERE messagestatus =  0 ORDER BY id ASC

**Comment by adityagokula2210** [comment]
We think that the **Instant Run** feature of **Android Studio** is enabled. Please disable the same and check in case you still get the error.
