### ISSUE TITLE
CometChat screen takes time to load

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#21]
Hello
When I start cometchat screen it takes almost 3-4 seconds to start the screen
that much delay is not a good for any UI
please suggest some solution

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

Yes, It takes 2-3 seconds to launch CometChat window as we have to initialize the CometChat Services before launching. We are working on reducing the launch time it should be live in couple of releases, we will keep you posted on the progress.

Thank You.
