### ISSUE TITLE
Report user functionality

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#24]
We would like to have report user functionality in CometChat.
Is there any way in CometChat to use or add this functionality from backend

**Comment by mehtanishant** [comment]
Hello @imdBhargav ,

We would like to inform that you can use the Report Conversation feature from the CometChat Administration Panel > Features section. You need to configure the email address of the user who is supposed to receive the email alerts regarding the Report Conversation. Once configured, the user can report a conversation and an email alert will be sent on that particular email id. We have also attached a pdf regarding the Report Conversation.

[What is Report Conversation.pdf](https://github.com/CometChat/android-chat-sdk-demo/files/2905698/What.is.Report.Conversation.pdf)


Please note that there might be a possibility that the email will be received under the spam section of the inbox.
Feel free to contact us if you have any other queries.
