### ISSUE TITLE
no such table: conversation Exception

### ISSUE THREAD

**Issue by Pankaj0307** [cometchat-go/android-chat-sdk-demo#3]
Hi, 
I am getting below sqlite exception while calling the  below method : 
## cometChat.launchCometChat()

no such table: conversation (code 1): , while compiling: SELECT * FROM `conversation` ORDER BY `timestamp` DESC;)

**Comment by anantgarg** [comment]
We think that the Instant Run feature of Android Studio is enabled. Please disable the same and check in case you still get the error.

This error has also been resolved in our sdk Version 7.5. Please try with the latest version and let us know if you are still facing this issue. You can create a support ticket: https://www.cometchat.com/contact-support as we may need some additional data.
