### ISSUE TITLE
Always get Error In Connection when Initialize Chat

### ISSUE THREAD

**Issue by ayyash-ayyub** [cometchat-go/android-chat-sdk-demo#4]
Hi!
Im just trying to test this project using my API key and License key but always getting this error when running it on android studio 👎 
screenshoot 

![e95aee17-8b1a-46a9-9e33-c5baeb046af5](https://user-images.githubusercontent.com/15217489/44353478-49ea1d80-a4d1-11e8-8306-33a986c352ba.jpg)

did i miss something?

**Comment by shettysujeet** [comment]
@simbelekete : We have tested the scenario using our License Key and CometChat API Key and is working fine. It would be great if you could provide us with the logs generated in Android Studio which will help us better understand the problem and check this at our end. You can also create a support ticket for the same using the below link:

https://www.cometchat.com/contact-support

Thanks

**Comment by ayyash-ayyub** [comment]
Thank you for your reply,

 I'd fix the initialize chat issue by put server IP on cometChat Inilization line code.
the next problem is android apps cannot open the Chat, and the log show message like this :
 Login Fail : {"code":"206","message":"<script>console.log( 'Comet Chat Init ' );<\/script>{\"basedata\":\"0\",\"version\":\"7.0.14\"}"}

 Login Fail : {"code":"203","message":"Sorry, CometChat needs to be upgraded on the site to use this app."}

**Comment by adityagokula2210** [comment]
@simbelekete 

It seems that you are using the self-hosted version of CometChat. However, this version of the sample app is designed for CometChat Cloud users. Please get in touch with our support team for us to better help you with the same. you can create a support ticket using the below link:

https://www.cometchat.com/contact-support

Thanks!!

**Comment by ayyash-ayyub** [comment]
hi, @adityagokula2210 
until now Im still waiting reply from contact support. they provide a solution and even snapshot code sample, but still not working.
here a new error that I found:
 {"code":"206","message":"<br \/>\n<b>Warning<\/b>: error_log(\/var\/www\/html\/cometchat\/writable\/logs\/error_7.0.14.log): failed to open stream: Permission denied in <b>\/var\/www\/html\/cometchat\/cometchat_shared.php<\/b> on line <b>2877<\/b><br \/>\n{\"basedata\":\"0\",\"version\":\"7.0.14\"}"} 
error_log(/var/www/html/cometchat/writable/logs/error_7.0.14.log): failed to open stream: Permission denied in /var/www/html/cometchat/cometchat_shared.php on line 2877


and these instructions for self_hosting is not working as well. I'm following the instruction and have an error in apps when running Android Apps. the following error is :

Login Fail : {"code":"200","message":"com.android.volley.ServerError"}

**Comment by adityagokula2210** [comment]
@simbelekete 

We deeply regret the inconvenience caused to you. However, as mentioned earlier these sample apps are for CometChat Cloud version and only the issues related to these apps are handled here. Unfortunately, you will have to wait for our support team to respond to you. We have escalated the query to our self-hosted team and they will get back to you as soon as possible.

Thanks for your patience.
