### ISSUE TITLE
Audio/Video call : Error on OnePlus 6

### ISSUE THREAD

**Issue by g-balas** [cometchat-go/android-chat-sdk-demo#5]
Hello,
At my first try on using CometChat Demo sample, I can't get audio neither video call to work.
Even if I already reached the support, I still add this issue here to warn other developers.

Bug difficult to explain, better check this : https://vimeo.com/286914674
Tested on : Nexus 4 v5.1.1 Android - OnePlus 6 OxygenOS 5.1.9

I have even tried with my iPhone X... audio / video is not properly working.

This is a dealbreaker for me, because I am using cometchat for theses features.

[stack_trace_test_cometchatsample_14_08_2018.txt](https://github.com/CometChat/android-chat-sdk-demo/files/2324787/stack_trace_test_cometchatsample_14_08_2018.txt)
[stack_trace_test_cometchatsample_14_08_2018_B.txt](https://github.com/CometChat/android-chat-sdk-demo/files/2324788/stack_trace_test_cometchatsample_14_08_2018_B.txt)

Regards,
Guillaume

**Comment by adityagokula2210** [comment]
@g-balas 

We have checked this issue at our end and have been able to replicate this too. There is sone issue with acquiring the audio stream from the OnePlus 6 device. We have taken this up on priority and will keep you updated on our progress.

We have tested this on other devices and have found that the calls are working as expected. We suggest you try the calling feature using other devices and we are sure that the calls will work as expected.

regarding the calls not working in OnePlus6, we are investigating the issue and will keep you posted regarding the same.

Thanks for your patience.

**Comment by adityagokula2210** [comment]
@g-balas 

We have fixed the issue at our end and are currently getting the fix tested by our QA team. We plan to release the fix for the same as a part of our next release which should be done on Monday or latest by Tuesday end of the day

We thank you for your patience and we will surely update you once the new version of the SDK is live.

Thanks

**Comment by adityagokula2210** [comment]
@g-balas 
We have released a new version of the Android SDK(version 7.13.0). Please migrate to the latest version using the Gradle dependencies. This issue has been resolved and the Calls now work fine with OnePlus 6.

Please check the same at your end and do get back to us in case you face any other issues.

Thanks for your patience.

**Comment by g-balas** [comment]
Just tested, works fine now. Thanks for your good reaction time.

**Comment by anantgarg** [comment]
Great! Let us know if you need anything else.
