### ISSUE TITLE
Multiple logins not working in Single device

### ISSUE THREAD

**Issue by Mohsin92** [cometchat-go/android-chat-sdk-demo#6]
I tried with demo and run on single device with separate login 
but both time its shows as single user only chatting.

e.g:
Login with superhero1 in cometchat and chat with superhero2 
now i am login with superhero2 but I can see same list or chat which is done in superhero1 
its visible on right side only.
please guide me with this issue.

**Comment by jitvarpatil** [comment]
You can implement the following method to clear the data manually.

private static void clearDataBase() {
SugarRecord.deleteAll(OneOnOneMessage.class);
SugarRecord.deleteAll(Groups.class);
SugarRecord.deleteAll(Conversation.class);
SugarRecord.deleteAll(GroupMessage.class);
SugarRecord.deleteAll(Status.class);
SugarRecord.deleteAll(Contact.class);
SugarRecord.deleteAll(Bot.class);
}  

You can call the above method in the success of login. We will be fixing this issue in the upcoming release and it will be handled by CometChat SDK.

**Comment by Mohsin92** [comment]
@jitvarpatil : Thank you for this solution it works
but please tel me when new version for Comet Chat will release ?

**Comment by jitvarpatil** [comment]
The new version with this fix will be out next week. Feel free to contact us if you have any other queries.
