### ISSUE TITLE
ComectChat starts new activity stack every time

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#8]
If I have 5 users in my app and click on 1st user to chat with him.
It starts cometchat screen.
I came back from chat to my app 
now I click on 2nd user to chat with him
It starts chat with 2nd user
Now coming back,
it will show the main cometchat screen, then 1st user chat window and then again main screen and then it came to my app.

Everytime i starts cometchat, It creates a new activity task and not replacing an existing one.
Or may be on exiting cometchat, its not kill that app.

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 
Thank you for contacting us, we are analyzing the above-mentioned issue and will provide you with a solution shortly.

**Comment by imdBhargav** [comment]
Thanks @jitvarpatil

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 

We have tested analyzed the issue you are facing. It seems that you are giving multiple calls to launchCometChat() method and multiple windows are getting added in the stack. However, we have addressed this issue at our end and the fix will be available in our next release.

Feel free to contact us for any other queries or issue.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil Thanks for your reply

Can you please suggest any other possible way to open a chat for different users without giving multiple calls to launchCometChat() as for as I know the only way to open a chat is calling launchCometChat through uid

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 

Yes, You're correct. The only way to launch CometChat is using launchCometChat() method. You can add the following line of code in the manifest file to fix the issue you are facing.

`android:launchMode="singleInstance"`

In CometChatActivity & CCSingleChatActivity tags. Feel free to contact us for any other queries or issue.

Thank You
