### ISSUE TITLE
How to get UID of user in CCSingleChatActivity

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#9]
I have imported 'CometChatUI' module in my project to modify some UI.
My requirement is
suppose my name is 'A' and I am chatting with user named 'B'. 
In a One-to-one chat, when I clicked on View profile to see 'B' user's profile. I want to redirect the user A to my app to see the user B's profile. I do not want to open CometChat profile screen

I am registering and login  an user into CometChat from uid. (and this uid is user id from our app) 
Now in CCSingleChatActivity I want to get that uid from which the user B logged in. 
But unfortunatlely, I am not getting that uid of user B.

I have tried 
contactId, 
contact.cometid, 
contact.id  

But not getting the uid from which user is logged into the CometChat.

Can you please advice how to get uid of user in CometChat

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

You are getting the UID in contact list jsonObject you receive in gotOnlineList() callback of subscribe method, You can find that in CCSubcribe.class. Following in the Contact object you get in the gotOnlineList() method:

`{"id":"***","uid":"****","n":"*****","l":"","a":"\"\"","d":0,"s":"offline","m":"I'm offline","g":"","ls":"","lstn":"","ch":"*******************","rdrs":0,"role":"******","custom":""}`

However we are not saving UID in local Database and hence you are not able to access that using the contact object in CCSingleChatActivity. You can create a new database field and access it in CCSingleChatActivity. 

If you have any further queries. you can schedule a session and we can work on resolving your issue. You can schedule a session at the following link:

https://www.cometchat.com/schedule-session/

Thank You
